name: Report PR Coverage

on:
  workflow_run:
    workflows: ["Lint and Test PR"]
    types:
      - completed

jobs:
  pr-coverage-report:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage-latest
      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: coverage-latest/coverage-summary.json
          json-final-path: coverage-latest/coverage-final.json
          file-coverage-mode: "all"